name: kubectl-test

env:
  CI: true
on:
  workflow_dispatch:

jobs:
  kubectl:
    name: kubectl
    runs-on: ubuntu-latest

    steps:
    - name: set context
      uses: azure/k8s-set-context@v4
      with:
        method: service-principal
        cluster-type: arc
        cluster-name: dida-aks-g4-japaneast-test
        resource-group: DataAnalysisTest

    - name: kubectl command Test
      run: |-
        kubectl config current-context
