name: kubectl wf test

env:
  CI: true
on:
  workflow_dispatch:

jobs:
  kubectl:
    name: kubectl
    runs-on: ubuntu-latest

    steps:
      - name: command
        run: |-
          test=${{  ("dida-test"=="dida" && "success") ||  "-test" }}
          echo $test
